package tang.model;

public class Role {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.ID
     *
     * @mbg.generated Wed Mar 15 21:41:14 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.TEXT
     *
     * @mbg.generated Wed Mar 15 21:41:14 CST 2017
     */
    private String text;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.ID
     *
     * @return the value of role.ID
     *
     * @mbg.generated Wed Mar 15 21:41:14 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.ID
     *
     * @param id the value for role.ID
     *
     * @mbg.generated Wed Mar 15 21:41:14 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.TEXT
     *
     * @return the value of role.TEXT
     *
     * @mbg.generated Wed Mar 15 21:41:14 CST 2017
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.TEXT
     *
     * @param text the value for role.TEXT
     *
     * @mbg.generated Wed Mar 15 21:41:14 CST 2017
     */
    public void setText(String text) {
        this.text = text == null ? null : text.trim();
    }
}